---
- hosts: redmine
  sudo: yes
  vars_file:
    - vars/password.yml
  tasks:
    - name: install packages
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - curl
        - git
        - imagemagick
        - libmagickwand-dev
        - mysql-server
        - libmysqlclient-dev
        - openssl
        - apache2
        - libcurl4-gnutls-dev
        - libapache-dbi-perl
        - libapache2-mod-perl2
        - libdbd-mysql-perl
        - libauthen-simple-ldap-perl

    - name: install ruby 2.0
      shell: curl -sSL https://get.rvm.io | bash -s stable --ruby=2.0.0

    - name: get redmine source
      git: repo=https://github.com/redmine/redmine dest=/opt/redmine

    - name: ensure directories
      file: path={{item}} owner="www-data" group="www-data" mode=0755 state=directory recurse=yes
      with_items:
        - /opt/redmine/tmp/pdf
        - /opt/redmine/public/plugin_assets
        - /opt/redmine/files
        - /opt/redmine/log
        - /opt/redmine/repos/git

    - name: ensure mysql is up
      service: name=mysql state=started

    - name: update mysql root password
      mysql_user: name=root password={{ ROOT_DB_PASS }}

    - name: ensure mysql db
      mysql_db: name=redmine state=present

    - name: "ensure mysql user: redmine"
      mysql_user: name=redmine
        password={{REDMINE_DB_PASS}}
        priv="redmine.*:ALL" host=localhost state=present

    - name: config redmine
      template: src=templates/database.yml dest=/opt/redmine/config/database.yml

    - name: install bundler gem
      gem: name=bundler state=present

    - name: install other dependencies
      script: script/initDB.sh